- name: Copy initial world
  become: yes
  become_user: root
  copy:
    src: "{{ server.initial_world_local_path }}/"
    dest: /home/steam/initial_world/
    owner: steam
    group: steam
    mode: u=rw,g=r,o=r

- name: Restore initial world
  become: yes
  become_user: root
  shell: |
    chmod +x menu.sh
    chmod +x lib/*.sh
    lib/restore.sh --backup_path /home/steam/initial_world && echo "restored" >> /home/steam/initial_world.restored
  args:
    chdir: "{{ server_repo.dest }}"
    creates: /home/steam/initial_world.restored