- name: Restore world
  hosts: aws_ec2
  remote_user: ubuntu

  tasks:
    - include_vars:
        dir: config
        extensions:
          - 'yaml'
        ignore_unknown_extensions: True

    - include: tasks/restore.yaml
      vars:
        backup_path: "{{ backup_path | default(/mnt/goofys/{{ goofys.bucket }}/{{ server.world_name }})"